#
# Site settings
#
title: Web Accessibility Guidelines
url: https://stevenmouret.github.io
baseurl: /web-accessibility-guidelines
author: Steven Mouret

markdown: kramdown
highlighter: rouge
kramdown:
  auto_ids: true
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  input: GFM
  hard_wrap: false
  footnote_nr: 1
  parse_block_html: true
  syntax_highlighter: rouge

sass:
    sass_dir: _sass

#
# Collections
#
collections:
  doc:
    output: true
    permalink: /:path.html
  posts:
    output: true
    permalink: posts/:title:output_ext

#
# Default values
#
defaults:
  -
    scope:
      path: ""
      type: doc
    values:
      layout: "doc"
  -
    scope:
      path: ""
      type: pages
    values:
      layout: "doc"

#
# Plugins
#
plugins:
  - jekyll-sitemap
  - jekyll-paginate

paginate: 10 # jekyll-paginate > items per page
paginate_path: "/posts/page:num/"
